env: MISEnv-v0
seed: 42
n_val_episodes: 20
val_freq: 1024
num_envs: 1
policy_kwargs:
  pooling_type: mean
  embed_dim: 128
  network_kwargs:
    network: GAT
    num_layers: 2

PPO: 
  timesteps: 100000
  seed: 42
  learning_rate: 1e-5
  gamma: 1
  n_steps: 1024

eval_seed: 1
n_eval_episodes: 100
use_masking: True